<?php

return [
    'shortcuts' => [
        'ventas.altas' => [
            'label' => 'Nueva Venta',
            'icon' => 'fa-shopping-cart',
            'color' => 'card-sale',
            'roles' => ['*'],
            'modulos' => ['*'],
        ],
        'productos.consultaprecio' => [
            'label' => 'Consulta Precios',
            'icon' => 'fa-usd',
            'color' => 'card-prod',
            'roles' => ['*'],
            'modulos' => ['*'],
        ],
        'productos.index' => [
            'label' => 'Productos',
            'icon' => 'fa-barcode',
            'color' => 'card-prod',
            'roles' => ['*'],
            'modulos' => ['*'],
        ],
        'clientes.index' => [
            'label' => 'Clientes',
            'icon' => 'fa-users',
            'color' => 'card-client',
            'roles' => ['*'],
            'modulos' => ['*'],
        ],
        'compras.index' => [
            'label' => 'Compras',
            'icon' => 'fa-truck',
            'color' => 'card-buy',
            'roles' => ['*'],
            'modulos' => ['*'],
        ],
        'sucursales.lista_remitos' => [
            'label' => 'Remitos InterSuc.',
            'icon' => 'fa-truck',
            'color' => 'card-buy',
            'roles' => ['*'],
            'modulos' => ['*'],
        ],
        'facturas.index' => [
            'label' => 'Facturas',
            'icon' => 'fa-file-text-o',
            'color' => 'card-inv',
            'roles' => ['*'],
            'modulos' => ['*'],
        ],
        'ctrol_stock.index' => [
            'label' => 'Control Stock',
            'icon' => 'fa-cubes',
            'color' => 'card-stock',
            'roles' => ['*'],
            'modulos' => ['*'],
        ],
        'ot.consulta' => [
            'label' => 'Consulta OT',
            'icon' => 'fa-eye',
            'color' => 'card-opt',
            'roles' => ['*'],
            'modulos' => ['optica'],
        ],
        'ot.index' => [
            'label' => 'Ordenes Trabajo',
            'icon' => 'fa-wrench',
            'color' => 'card-opt',
            'roles' => ['*'],
            'modulos' => ['optica'],
        ],
        'cajas.altas' => [
            'label' => 'Mov. Caja',
            'icon' => 'fa-money',
            'color' => 'card-admin',
            'roles' => ['ADM'],
            'modulos' => ['*'],
        ],
        'cajas.transferencias' => [
            'label' => 'Transf. Cajas',
            'icon' => 'fa-exchange',
            'color' => 'card-admin',
            'roles' => ['ADM'],
            'modulos' => ['*'],
        ],
        'cajas.ventas' => [
            'label' => 'Informe Ventas',
            'icon' => 'fa-line-chart',
            'color' => 'card-sale',
            'roles' => ['ADM'],
            'modulos' => ['*'],
        ],
        'estadisticas.consolidado' => [
            'label' => 'Consolidado',
            'icon' => 'fa-bar-chart',
            'color' => 'card-admin',
            'roles' => ['ADM'],
            'modulos' => ['*'],
        ],
    ],
];
